name: The Fifth Day
favicon: null
layout_spectrum: 0.9942648217547685
typography_spectrum: 0.338273701723665
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5232164277695119
  lightness: 0.6853969495277852
  saturation: 0.3556945351883769
  rhythmicContrast: 0.5751119921915233
purpose: []
